{{- if .Values.minio.enabled }}
{{- $secretName := "minio-auth-secret" -}}
{{- $rootUser := "minioadmin" -}}
{{- $rootPassword := randAlphaNum 32 -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if $existingSecret -}}
  {{- $rootUser = index $existingSecret.data "rootUser" | b64dec -}}
  {{- $rootPassword = index $existingSecret.data "rootPassword" | b64dec -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app: minio
type: Opaque
data:
  rootUser: {{ $rootUser | b64enc | quote }}
  rootPassword: {{ $rootPassword | b64enc | quote }}
{{- end }}
