{{- if and .Values.postgresql.enabled .Values.postgresql.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-nodeport
  labels:
    app: postgres
    cluster-name: {{ .Release.Name }}-db
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    application: spilo
    cluster-name: {{ .Release.Name }}-db
    spilo-role: master
{{- end }}
