apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-langfuse-secret
type: Opaque
stringData:
  nextauth-secret: {{ .Values.secrets.langfuseNextauthSecret | quote }}
  salt: {{ .Values.secrets.langfuseSalt | quote }}
