{{- if .Values.caddyTailscale.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "platform.fullname" . }}-tailscale-data
  labels:
    app: caddy-tailscale
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.caddyTailscale.storage.size }}
{{- end }}
