image:
  repository: ghcr.io/gordon-control-plane
  tag: latest
  pullPolicy: IfNotPresent

ateapi:
  replicaCount: 1

atecontroller:
  replicaCount: 1

atelet:
  enabled: true

postgres:
  host: "agent-platform-db"

tls:
  create: true
  secretName: agent-substrate-tls
