{{- if .Values.atelet.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: atelet
  labels:
    {{- include "agent-substrate.labels" . | nindent 4 }}
    app.kubernetes.io/component: atelet
spec:
  selector:
    matchLabels:
      {{- include "agent-substrate.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: atelet
  template:
    metadata:
      labels:
        {{- include "agent-substrate.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: atelet
    spec:
      serviceAccountName: agent-substrate-sa
      hostPID: true
      containers:
      - name: atelet
        image: "{{ .Values.image.repository }}/atelet:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/usr/local/bin/atelet"]
        securityContext:
          privileged: true
        args:
        - --ateapi-address=ateapi:50051
        - --gcp-auth-for-image-pulls=false
        - --ateapi-ca-file=/etc/tls/bundle.pem
        - --grpc-server-cred-bundle=/etc/tls/bundle.pem
        - --client-ca-certs=/etc/tls/bundle.pem
        - --ateapi-server-name=ateapi
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: host-var-run
          mountPath: /var/run
        - name: host-sys
          mountPath: /sys
          readOnly: true
        - name: tls
          mountPath: /etc/tls
          readOnly: true
      volumes:
      - name: host-var-run
        hostPath:
          path: /var/run
      - name: host-sys
        hostPath:
          path: /sys
      - name: tls
        secret:
          secretName: agent-substrate-tls
{{- end }}
