apiVersion: apps/v1
kind: Deployment
metadata:
  name: atecontroller
  labels:
    {{- include "agent-substrate.labels" . | nindent 4 }}
    app.kubernetes.io/component: atecontroller
spec:
  replicas: {{ .Values.atecontroller.replicaCount }}
  selector:
    matchLabels:
      {{- include "agent-substrate.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: atecontroller
  template:
    metadata:
      labels:
        {{- include "agent-substrate.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: atecontroller
    spec:
      serviceAccountName: agent-substrate-controller-sa
      containers:
      - name: atecontroller
        image: "{{ .Values.image.repository }}/atecontroller:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

        command: ["/usr/local/bin/atecontroller"]
        args:
        - "--ateapi-conn-spec=ateapi:50051"
        - "--ateapi-client-cert=/etc/tls/bundle.pem"
        - "--ateapi-ca-file=/etc/tls/bundle.pem"
        - "--ateapi-server-name=ateapi"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: k8s.namespace.name=$(POD_NAMESPACE),k8s.pod.name=$(POD_NAME),k8s.pod.uid=$(POD_UID),service.instance.id=$(POD_UID)
        volumeMounts:
        - name: tls
          mountPath: /etc/tls
          readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: agent-substrate-tls
