apiVersion: apps/v1
kind: Deployment
metadata:
  name: atecontroller
  labels:
    {{- include "agent-substrate.labels" . | nindent 4 }}
    app.kubernetes.io/component: atecontroller
spec:
  replicas: {{ .Values.atecontroller.replicaCount }}
  selector:
    matchLabels:
      {{- include "agent-substrate.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: atecontroller
  template:
    metadata:
      labels:
        {{- include "agent-substrate.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: atecontroller
    spec:
      serviceAccountName: agent-substrate-sa
      containers:
      - name: atecontroller
        image: "{{ .Values.image.repository }}/atecontroller:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/usr/local/bin/atecontroller"]
        args:
        - "--ateapi-conn-spec=ateapi:50051"
        - "--ateapi-client-cert=/etc/tls/bundle.pem"
        - "--ateapi-ca-file=/etc/tls/bundle.pem"
        - "--ateapi-server-name=ateapi"
        volumeMounts:
        - name: tls
          mountPath: /etc/tls
          readOnly: true
      volumes:
      - name: tls
        secret:
          secretName: agent-substrate-tls
