apiVersion: v1
kind: Secret
metadata:
  name: agent-substrate-secrets
  labels:
    {{- include "agent-substrate.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | quote }}
  minio-accessKey: {{ .Values.minio.accessKey | quote }}
  minio-secretKey: {{ .Values.minio.secretKey | quote }}
