{{- if .Values.tls.create }}
{{- $secretName := .Values.tls.secretName | default "agent-substrate-tls" }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $caCert := "" }}
{{- $tlsCert := "" }}
{{- $tlsKey := "" }}
{{- $jwtKey := "" }}
{{- if $secret }}
{{- $caCert = index $secret.data "ca.crt" | b64dec }}
{{- $tlsCert = index $secret.data "tls.crt" | b64dec }}
{{- $tlsKey = index $secret.data "tls.key" | b64dec }}
{{- $jwtKey = index $secret.data "jwt.pem" | b64dec }}
{{- else }}
{{- $ca := genCA "agent-substrate-ca" 365 }}
{{- $cert := genSignedCert "ateapi" nil (list "ateapi" "ateapi.default.svc.cluster.local") 365 $ca }}
{{- $caCert = $ca.Cert }}
{{- $tlsCert = $cert.Cert }}
{{- $tlsKey = $cert.Key }}
{{- $jwtKey = randAlphaNum 64 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-substrate.labels" . | nindent 4 }}
type: Opaque
data:
  bundle.pem: {{ printf "%s\n%s\n%s" $tlsCert $tlsKey $caCert | b64enc | quote }}
  ca.crt: {{ $caCert | b64enc | quote }}
  tls.crt: {{ $tlsCert | b64enc | quote }}
  tls.key: {{ $tlsKey | b64enc | quote }}
  jwt.pem: {{ "{}" | b64enc | quote }}
  auth.yaml: {{ "actorIdentityJWTProvider: \"dummy\"\njwtProviders:\n- name: \"dummy\"\n  issuer: \"https://dummy\"\n  audiences: [\"dummy\"]\n" | b64enc | quote }}
{{- end }}
